package by.mycloud_zapchast.www.controller;

/**
 * 
 * @author Vitamin_XO
 *
 */
public enum CommandName {

	GO_TO_STANDART_PRE_SEARCH, ERROR_PAGE, STANDART_SEARCH, GO_TO_DOCUMENTATION, GO_TO_REGISTRATION_1_PAGE,
	GO_TO_REGISTRATION_2_PAGE, REGISTRATION_NEW_USER, AUTHORIZATION, GO_TO_AUTHORIZATION_PAGE,
	GO_TO_APPLICATION_PRE_SEARCH, APPLICATION_SEARCH, SIGN_OUT
}
