package by.hodyko.www.controller;

public enum CommandName {
	
	REGISTRATION_PAGE, AUTHORIZATION_PAGE, REGISTRATION_NEW_USER, AUTHORIZATION_USER, UNKNOWN_COMMAND,
	GO_TO_MAIN_PAGE, ADD_NEWS, ADD_NEWS_PAGE, CHANGE_LOCAL, GO_CONCRETE_NEWS, DELETE_NEWS, UPDATE_NEWS_PAGE, UPDATE_NEWS

}
